apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ai-task-platform
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9haV90YXNrcw==
  
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  
  JWT_SECRET: c3VwZXJfc2VjcmV0X2p3dF9rZXlfaGVyZQ==
